Title: Data for Good at Meta
Description: |
    The Data for Good at Meta program includes tools built from
    de-identified data on our platform, as well as tools that we
    develop using satellite imagery and other publicly available
    sources. When data is shared responsibly with the communities
    that need it, it can improve wellbeing and save lives.
Logo: meta-logo.png
Datasets:
  - dataforgood-fb-hrsl
  - daylight-osm
