redirects:
  - source: /tag/sustainability/resources/index.html
    target: /tag/sustainability/usage-examples/index.html
  - source: /usda-naip/index.html
    target: /naip/index.html
  - source: /landsat-8/index.html
    target: /usgs-landsat/index.html
  - source: /collab/facebook/index.html
    target: /collab/meta/index.html    
  - source: /noaa-cmip5/index.html
    target: /noaa-uwpd-cmip5/index.html
